### ISSUE TITLE
TODO: Game Page

### ISSUE THREAD

**Issue by jmeuwissen** [jmeuwissen/crispy-memory#30]
- [ ] Create Game Page with div for potato and div for limbs

- [ ] populate divs with their respecive image elements

- [ ] allow clicking and dragging of limb elements
