### ISSUE TITLE
TODO: Wireframe

### ISSUE THREAD

**Issue by jmeuwissen** [jmeuwissen/crispy-memory#31]
- [x] Create account page mockup 

- [x] Game page mockup 

- [x] Gallery page mockup 

- [ ] Upload Images

- [ ] Label + describe elements of Create account page

- [ ] Label + describe elements of Game page

- [ ] Label + describe elements of Gallery page
